version: "3.8"

services:
    api:
        build: fifa-api
        container_name: fifa_api
        env_file: fifa-api/.env
        ports:
            - "5000:5000"
        networks:
            - app-network
    web:
        build:
            context: express-app
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        volumes:
            - ./express-app:/opt/express-app
        env_file: express-app/.env
        ports:
            - "80:8080"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
