version: "3.8"

services:
    api:
        build: 
            context: ./fifa-api
            dockerfile: Dockerfile
        container_name: FIFA_API
        restart: unless-stopped
        ports:
            - "$FLASK_RUN_PORT:$FLASK_RUN_PORT"
        environment:
            - FLASK_APP=$FLASK_APP
            - FLASK_ENV=$FLASK_ENV
            - FLASK_RUN_PORT=$FLASK_RUN_PORT
            - FLASK_RUN_HOST=$FLASK_RUN_HOST

    backend:
        depends_on:
            - api
        build:
            context: ./express-app
            dockerfile: Dockerfile
        container_name: express_app
        restart: unless-stopped
        volumes:
            - /server/node_modules
            - build_volume:/server/build
        ports:
            - "$NODE_EXPOSED_PORT:$NODE_DOCKER_PORT"
        environment:
            - NODE_ENV=$NODE_ENV
            - APP_NAME=$NODE_APP_NAME
            - HOST=$NODE_HOST
            - PORT=$NODE_DOCKER_PORT
            - NODE_EXPOSED_PORT=$NODE_EXPOSED_PORT
            - BUILD_PATH=$BUILD_PATH
            - FLASK_URL=$FLASK_RUN_HOST:$FLASK_RUN_PORT

    nginx-proxy:
        depends_on:
            - backend
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "$PROXY_PORT:$PROXY_PORT"

volumes:
    build_volume: